fun main() {
    val t = Baggage<Product>()
    println(t.isEmpty)
    t.push(Food.Broccoli())
    t.push(Food.Broccoli())
    t.push(Food.Broccoli())
    t.push(Food.Broccoli())
    t.push(Food.Broccoli())
    t.push(Food.Potato())
    t.printProductList()
    t.pop()
    t.pop()
    t.printProductList()
    t.push(Food.Sugar())
    t.printProductList()
    println(t.isEmpty)
    t.pop()
    t.pop()
    t.pop()
    t.pop()
    t.pop()
    t.pop()
    println(t.isEmpty)
    t.printProductList()
}